# src/category_rules.py

CATEGORY_RULES = {
   "rating_manipulation": {
    "keywords": [
        "yorumum üstte gözüksün",
        "yorumum gözüksün",
        "yorum gözüksün",
        "yorum görünsün",
        "yorumum görünsün",
        "üstte gözüksün",
        "üste çıksın",
        "yukarı çıksın",
        "yukarıya çıksın",
        "öne çıksın",
        "başa çıksın",
        "başta gözüksün",
        "sırf üstte dursun",
        "üstte dursun diye",
        "görünsün diye",
        "gözüksün diye",
        "yorum öne çıksın",
        "yorum yukarı çıksın",
        "yorumum okunsun diye",
        "sırf görünsün diye",
        "sırf gözüksün diye"
    ],
    "near": [
        {"terms": ["5 yıldız", "gözüksün"], "max_distance": 8},
        {"terms": ["5 yıldız", "görünsün"], "max_distance": 8},
        {"terms": ["5 yıldız", "üstte"], "max_distance": 8},
        {"terms": ["5 yıldız", "üste"], "max_distance": 8},
        {"terms": ["5 yıldız", "yukarı"], "max_distance": 8},
        {"terms": ["5 yıldız", "çıksın"], "max_distance": 8},
        {"terms": ["beş yıldız", "gözüksün"], "max_distance": 8},
        {"terms": ["beş yıldız", "görünsün"], "max_distance": 8},
        {"terms": ["yorum", "üstte"], "max_distance": 5},
        {"terms": ["yorum", "üste"], "max_distance": 5},
        {"terms": ["yorum", "gözüksün"], "max_distance": 5},
        {"terms": ["yorum", "görünsün"], "max_distance": 5},
        {"terms": ["yorum", "okunsun"], "max_distance": 5},
        {"terms": ["sırf", "5 yıldız"], "max_distance": 6},
        {"terms": ["sırf", "beş yıldız"], "max_distance": 6}
    ],
    "regex": [
        r"\b(5|beş)\s*yıldız\s+(verdim|veriyorum|verdım).{0,60}\b(gözüksün|görünsün|üstte|üste|yukarı|çıksın|okunsun)\b",
        r"\b(gözüksün|görünsün|üstte|üste|yukarı|çıksın|okunsun).{0,60}\b(5|beş)\s*yıldız\b",
        r"\byorum\w*.{0,30}\b(gözüksün|görünsün|üstte|üste|yukarı|çıksın|okunsun)\b"
    ],
    "fuzzy": []
},

    "reklam": {
        "keywords": [
            "reklam",
            "reklamından kurtulsam",
            "reklamdan kurtulsam",
            "şu oyunun reklamından bir kurtulsam",
            "reklam belasından kurtulsam",
            "reklamlar",
            "reklam çıkıyor",
            "reklam geliyor",
            "reklam veriyor",
            "çok reklam",
            "fazla reklam",
            "aşırı reklam",
            "sürekli reklam",
            "bitmeyen reklam",
            "uzun reklam",
            "reklam süresi",
            "video reklam",
            "reklam izletiyor",
            "reklam izlemek zorunda",
            "her bölümde reklam",
            "her levelde reklam",
            "her oyunda reklam",
            "ikide bir reklam",
            "iki de bir reklam",
            "reklamdan oynanmıyor",
            "reklam yüzünden oynanmıyor",
            "reklamı azaltın",
            "reklamları azaltın",
            "reklam kaldırın",
            "reklam kalksın",
            "reklam çıkmasın",
            "reklam engeli",
            "reklam sorunu",
            "reklam problemi",
            "reklam tuzağı",
            "ads",
            "ad not ready",
            "advertisement"
        ],
        "near": [
            {"terms": ["her", "reklam"], "max_distance": 4},
            {"terms": ["bölüm", "reklam"], "max_distance": 5},
            {"terms": ["reklam", "kurtulsam"], "max_distance": 6},
            {"terms": ["reklamından", "kurtulsam"], "max_distance": 6},
            {"terms": ["level", "reklam"], "max_distance": 5},
            {"terms": ["seviye", "reklam"], "max_distance": 5},
            {"terms": ["oyun", "reklam"], "max_distance": 5},
            {"terms": ["sürekli", "reklam"], "max_distance": 4},
            {"terms": ["reklam", "çok"], "max_distance": 3},
            {"terms": ["reklam", "fazla"], "max_distance": 3},
            {"terms": ["reklam", "aşırı"], "max_distance": 3},
            {"terms": ["reklam", "uzun"], "max_distance": 4},
            {"terms": ["reklam", "bitmiyor"], "max_distance": 4},
            {"terms": ["reklam", "çıkıyor"], "max_distance": 4},
            {"terms": ["reklam", "geliyor"], "max_distance": 4},
            {"terms": ["reklam", "izletiyor"], "max_distance": 4},
            {"terms": ["video", "reklam"], "max_distance": 3},
            {"terms": ["tanıtım", "reklam"], "max_distance": 3}
        ],
        "regex": [],
        "fuzzy": [
            "reklam", "reklem", "reklm", "reklamm"
        ]
    },

   "yaniltici_reklam_tanitim": {
    "keywords": [
        "reklamlarda gösterdikleri oyunları oynatmıyorlar",
        "reklamlarda gösterilen oyun yok",
        "görselle oyunun alakası yok",
        "görsel ile oyunun alakası yok",
        "görsellerle oyunun alakası yok",
        "görsel başka oyun başka",
        "reklamda başka oyun var",
        "reklamla oyunun alakası yok",
        "reklamdaki gibi değil",
        "reklamdakiyle alakası yok",
        "reklamdaki ile alakası yok",
        "reklamdaki oyun yok",
        "reklamdakiyle aynı değil",
        "reklamdaki ile aynı değil",
        "reklam başka oyun başka",
        "reklam farklı oyun farklı",
        "reklamda gösterilen yok",
        "reklamda gösterilen oyun değil",
        "reklamda gördüğüm oyun değil",
        "tanıtımdaki gibi değil",
        "tanıtımdakiyle alakası yok",
        "tanıtıldığı gibi değil",
        "görseldeki oyun yok",
        "görselle alakası yok",
        "fotoğraflardaki gibi değil",
        "videodaki gibi değil",
        "videodakiyle alakası yok",
        "gösterilen oyun yok",
        "gösterdikleri oyun değil",
        "sahte reklam",
        "yalan reklam",
        "yanıltıcı reklam",
        "yalan tanıtım",
        "yalan görsel",
        "bambaşka oyun",
        "reklamdaki oyun çıkmadı"
    ],
    "near": [
        {"terms": ["reklamdaki", "alakası yok"], "max_distance": 6},
        {"terms": ["reklam", "gösterdikleri", "oynatmıyorlar"], "max_distance": 8},
        {"terms": ["reklamlarda", "gösterilen", "yok"], "max_distance": 8},
        {"terms": ["görsel", "oyun", "alakası yok"], "max_distance": 8},
        {"terms": ["görselle", "oyunun", "alakası yok"], "max_distance": 8},
        {"terms": ["reklamdaki", "farklı"], "max_distance": 5},
        {"terms": ["reklamdaki", "başka"], "max_distance": 5},
        {"terms": ["reklamdaki", "gibi değil"], "max_distance": 6},
        {"terms": ["reklamda", "gösterilen"], "max_distance": 6},
        {"terms": ["tanıtımdaki", "alakası yok"], "max_distance": 6},
        {"terms": ["tanıtımdaki", "farklı"], "max_distance": 5},
        {"terms": ["tanıtımdaki", "gibi değil"], "max_distance": 6},
        {"terms": ["görseldeki", "oyun yok"], "max_distance": 6},
        {"terms": ["videodaki", "gibi değil"], "max_distance": 6},
        {"terms": ["gösterilen", "oyun", "yok"], "max_distance": 7},
        {"terms": ["sahte", "reklam"], "max_distance": 4},
        {"terms": ["yalan", "reklam"], "max_distance": 4}
    ],
    "regex": [
        r"\breklamdaki.{0,50}\b(alakası yok|farklı|başka|gibi değil|aynı değil)\b",
        r"\breklamda gösterilen.{0,50}\b(yok|değil|farklı|başka)\b",
        r"\btanıtımdaki.{0,50}\b(alakası yok|farklı|başka|gibi değil|aynı değil)\b",
        r"\bvideodaki.{0,50}\b(alakası yok|farklı|başka|gibi değil|aynı değil)\b",
        r"\bgösterilen oyun.{0,30}\b(yok|değil|farklı|başka)\b",
        r"\breklamlarda.{0,60}\bgösterdikleri.{0,60}\boynatmıyorlar\b",
        r"\bgörsel\w*.{0,50}\boyun\w*.{0,50}\balakası yok\b",
        r"\b(sahte reklam|yalan reklam|yanıltıcı reklam|yalan tanıtım)\b"
    ],
    "fuzzy": [
        "aldatıcı", "kandırmaca", "dolandırıcılık"
    ]
},

    "guncelleme_sorunu": {
        "keywords": [
            "güncelleyemiyorum",
            "güncellenmiyor",
            "güncelleme yok",
            "güncelleme gelmiyor",
            "güncelleme yapamıyorum",
            "güncellemeden sonra",
            "son güncelleme",
            "yeni güncelleme",
            "güncelleme sonrası",
            "güncelleme ile bozuldu",
            "güncellemeden sonra bozuldu",
            "güncellemeden sonra açılmıyor",
            "güncellemeden sonra giremiyorum",
            "güncellemeden sonra kasıyor",
            "güncellemeden sonra donuyor",
            "güncellemeden sonra kapandı",
            "güncelleme mahvetti",
            "güncelleme oyunu bozdu",
            "güncelleme sorunu",
            "güncelleme problemi",
            "eski sürüm daha iyiydi",
            "güncelleme gelsin",
            "güncelleme yapmıyor",
            "güncellemeye geçmiyor",
            "güncelleme ekranı çıkmıyor",
            "güncelleme yaptığım halde",
            "güncelleme sonrası",
            "yeni sürüm kötü",
            "güncelleme geç geliyor",
            "güncelleme yapın",
            "düzeltme güncellemesi",
            "son sürüm bozuk"
        ],
        "near": [
            {"terms": ["güncelleme", "yok"], "max_distance": 4},
            {"terms": ["güncelleme", "gelmiyor"], "max_distance": 4},
            {"terms": ["güncelleme", "yapamıyorum"], "max_distance": 5},
            {"terms": ["güncelleme", "sorun"], "max_distance": 5},
            {"terms": ["güncelleme", "hata"], "max_distance": 5},
            {"terms": ["güncelleme", "bozuldu"], "max_distance": 6},
            {"terms": ["güncelleme", "bozdu"], "max_distance": 6},
            {"terms": ["güncelleme", "mahvetti"], "max_distance": 6},
            {"terms": ["güncelleme", "açılmıyor"], "max_distance": 6},
            {"terms": ["güncelleme", "giremiyorum"], "max_distance": 6},
            {"terms": ["güncelleme", "kapanıyor"], "max_distance": 6},
            {"terms": ["güncelleme", "grafik"], "max_distance": 6},
            {"terms": ["güncelleme", "ekran"], "max_distance": 6},
            {"terms": ["güncelleme", "kararma"], "max_distance": 6},
            {"terms": ["son güncelleme", "kötü"], "max_distance": 6},
            {"terms": ["son güncelleme", "bozdu"], "max_distance": 6}
        ],
        "regex": [],
        "fuzzy": [
            "güncellenmiyor", "güncelleyemiyorum"
        ]
    },

    "yeni_bolum_icerik_eksikligi": {
        "keywords": [
            "yeni bölüm gelmiyor",
            "yeni bölüm yok",
            "yeni bölüm bekliyorum",
            "yeni bölümler gelsin",
            "yeni seviye gelmiyor",
            "yeni seviyeler gelsin",
            "devamı gelmiyor",
            "oyun bitti",
            "seviye kalmadı",
            "yeni bölümler gelmeyecekse",
            "bölümde kaldık",
            "yeni bölüm beklemek",
            "bölüm kalmadı",
            "level kalmadı",
            "arena da bitti",
            "bölümleri bitirdim",
            "seviyeleri bitirdim",
            "son bölüm",
            "son seviyeye geldim",
            "devamını bekliyorum",
            "çok az bölüm",
            "bölüm az",
            "seviyeleri az",
            "içerik az",
            "yeni içerik yok",
            "yeni oyunlar bekliyoruz",
            "hep aynı içerik",
            "aynı etkinlikler",
            "yeni etkinlik gelmiyor",
            "yeni harita yok",
            "yeni görev yok",
            "eklenecek bölüm yok",
            "bitti devamı yok"
        ],
        "near": [
            {"terms": ["yeni", "bölüm", "gelmiyor"], "max_distance": 5},
            {"terms": ["yeni", "seviye", "gelmiyor"], "max_distance": 5},
            {"terms": ["yeni", "level", "gelmiyor"], "max_distance": 5},
            {"terms": ["bölüm", "kalmadı"], "max_distance": 4},
            {"terms": ["seviye", "kalmadı"], "max_distance": 4},
            {"terms": ["level", "kalmadı"], "max_distance": 4},
            {"terms": ["oyun", "bitti"], "max_distance": 4},
            {"terms": ["bölümler", "bitti"], "max_distance": 4},
            {"terms": ["seviyeler", "bitti"], "max_distance": 4},
            {"terms": ["devamı", "gelmiyor"], "max_distance": 4},
            {"terms": ["ne zaman", "gelecek"], "max_distance": 5},
            {"terms": ["çok az", "bölüm"], "max_distance": 4},
            {"terms": ["az", "bölüm"], "max_distance": 3},
            {"terms": ["yeni", "içerik"], "max_distance": 5},
            {"terms": ["yeni", "etkinlik"], "max_distance": 5}
        ],
        "regex": [],
        "fuzzy": []
    },

    "cihaz_goruntu_sorunu": {
        "keywords": [
            "siyah ekran",
            "her taraf bozuk görünüyor",
            "oyun telef oldu",
            "minecraft gibi oldu",
            "mine craft gibi oldu",
            "siyah efektler",
            "ekran siyah siyah",
            "ekran siyah",
            "ekran karardı",
            "ekran kararıyor",
            "ekran bozuldu",
            "ekran bozuk",
            "ekran kalitesi düştü",
            "ekran kalitesi bozuldu",
            "siyah pikseller",
            "görüntü bozuk",
            "görüntü bozuldu",
            "görüntü gitti",
            "görüntü karıştı",
            "grafikleri bozuk",
            "grafikler bozuldu",
            "grafikler gitti",
            "grafik sorunu",
            "grafik problemi",
            "resimler bozuldu",
            "resimler karıştı",
            "renkler karıştı",
            "renkler bozuldu",
            "yazılar okunmuyor",
            "yazılar karıştı",
            "yazılar birbirine girdi",
            "rakamlar görünmüyor",
            "rakamlar belli olmuyor",
            "simsiyah ekran",
            "simsiyah karışık bir ekran",
            "siyah karışık ekran",
            "telefonumda çalışmadı",
            "telefonumda açılmıyor",
            "cihazımda çalışmıyor",
            "uyumlu değil",
            "desteklemiyor",
            "yüklenemez",
            "telefon ısınıyor",
            "telefon kitleniyor",
            "telefon kasıyor",
            "telefon donuyor",
            "şarj yiyor",
            "şarj tüketiyor",
            "şarj bitiriyor",
            "oynanmıyor bu şekilde",
            "atari gibi oldu",
            "görsel bozuk",
            "çözünürlük bozuldu"
        ],
        "near": [
            {"terms": ["siyah", "ekran"], "max_distance": 3},
            {"terms": ["ekran", "bozuldu"], "max_distance": 4},
            {"terms": ["ekran", "karardı"], "max_distance": 4},
            {"terms": ["ekran", "siyah"], "max_distance": 4},
            {"terms": ["görüntü", "bozuk"], "max_distance": 4},
            {"terms": ["görüntü", "bozuldu"], "max_distance": 4},
            {"terms": ["görüntü", "karıştı"], "max_distance": 4},
            {"terms": ["grafik", "bozuk"], "max_distance": 4},
            {"terms": ["grafik", "bozuldu"], "max_distance": 4},
            {"terms": ["grafikler", "gitti"], "max_distance": 4},
            {"terms": ["renkler", "karıştı"], "max_distance": 4},
            {"terms": ["renkler", "bozuldu"], "max_distance": 4},
            {"terms": ["yazılar", "karıştı"], "max_distance": 5},
            {"terms": ["yazılar", "okunmuyor"], "max_distance": 5},
            {"terms": ["rakamlar", "görünmüyor"], "max_distance": 5},
            {"terms": ["telefon", "ısınıyor"], "max_distance": 4},
            {"terms": ["telefon", "kitleniyor"], "max_distance": 4},
            {"terms": ["telefon", "çalışmadı"], "max_distance": 5},
            {"terms": ["cihaz", "uyumlu değil"], "max_distance": 5},
            {"terms": ["telefon", "uyumlu değil"], "max_distance": 5},
            {"terms": ["tablet", "uyumlu değil"], "max_distance": 5},
            {"terms": ["cihaz", "desteklemiyor"], "max_distance": 5},
            {"terms": ["şarj", "yiyor"], "max_distance": 4},
            {"terms": ["şarj", "bitiriyor"], "max_distance": 4},
            {"terms": ["şarj", "tüketiyor"], "max_distance": 4}
        ],
        "regex": [],
        "fuzzy": [
            "çözünürlük"
        ]
    },

    "yukleme_acilis_sorunu": {
        "keywords": [
            "yüklenmiyor",
            "yüklemiyor",
            "yüklenme kısmında kalıyor",
            "açılmıyor",
            "açılmadı",
            "oyun açılmıyor",
            "oyun açılmadı",
            "uygulama açılmıyor",
            "oyuna giremiyorum",
            "oyuna girmiyor",
            "giriş yapamıyorum",
            "oyuna giriş yapamıyorum",
            "indirilmiyor",
            "indiremiyorum",
            "yükleyemiyorum",
            "60 da kalıyor",
            "100 de kalıyor",
            "yükleme ekranında kaldı",
            "ekranda kalıyor",
            "hata veriyor",
            "teknik hata",
            "oyuna girmeden atıyor",
            "uygulama çalışmıyor",
            "uygulamayı indiremedim",
            "oyun kapanıyor",
            "kapanıp duruyor",
            "girince kapanıyor",
            "açınca kapanıyor",
            "başlamıyor",
            "oyun başlamıyor",
            "takılı kalıyor",
            "loadingde kalıyor",
            "yüklenirken kalıyor"
        ],
        "near": [
            {"terms": ["oyun", "açılmıyor"], "max_distance": 4},
            {"terms": ["oyun", "açılmadı"], "max_distance": 4},
            {"terms": ["oyuna", "giremiyorum"], "max_distance": 4},
            {"terms": ["giriş", "yapamıyorum"], "max_distance": 4},
            {"terms": ["yüklenme", "kalıyor"], "max_distance": 5},
            {"terms": ["yükleme", "kalıyor"], "max_distance": 5},
            {"terms": ["60", "kalıyor"], "max_distance": 4},
            {"terms": ["100", "kalıyor"], "max_distance": 4},
            {"terms": ["uygulama", "çalışmıyor"], "max_distance": 4},
            {"terms": ["oyun", "kapanıyor"], "max_distance": 4},
            {"terms": ["girince", "kapanıyor"], "max_distance": 4},
            {"terms": ["açınca", "kapanıyor"], "max_distance": 4}
        ],
        "regex": [
            r"\b(indirilmiyor|yüklenmiyor|açılmadı|açılmıyor)\b"
        ],
        "fuzzy": [
            "açılmıyor", "acilmiyor", "yüklenmiyor", "yuklenmiyor",
            "giremiyorum", "indirilmiyor"
        ]
    },

    "performans_donma_kasma": {
        "keywords": [
            "kasıyor",
            "kasıyor",
            "donuyor",
            "dondu",
            "donma",
            "donup kalıyor",
            "takılıyor",
            "takılma oluyor",
            "lag yapıyor",
            "çok yavaş",
            "aşırı yavaş",
            "oyun yavaş",
            "geç açılıyor",
            "geç yükleniyor",
            "yüklenmesi uzun",
            "kasma oluyor",
            "aşırı kasıyor",
            "çok kasıyor",
            "oyun çok geç açılıyor",
            "şarj tüketiyor",
            "şarj yiyor",
            "ısındırıyor",
            "telefonu ısıtıyor",
            "performans kötü",
            "fps düşüyor",
            "3 fps",
            "scene transitions are too slow",
            "yavaşladı",
            "oyun yavaşladı",
            "akıcı değil",
            "ağır çalışıyor",
            "tepkiler geç geliyor"
        ],
        "near": [
            {"terms": ["çok", "kasıyor"], "max_distance": 3},
            {"terms": ["aşırı", "kasıyor"], "max_distance": 3},
            {"terms": ["fazla", "kasıyor"], "max_distance": 3},
            {"terms": ["oyun", "donuyor"], "max_distance": 4},
            {"terms": ["oyun", "yavaşladı"], "max_distance": 4},
            {"terms": ["çok", "yavaş"], "max_distance": 3},
            {"terms": ["geç", "açılıyor"], "max_distance": 4},
            {"terms": ["geç", "yükleniyor"], "max_distance": 4},
            {"terms": ["telefon", "ısınıyor"], "max_distance": 4},
            {"terms": ["telefon", "ısıtıyor"], "max_distance": 4},
            {"terms": ["şarj", "yiyor"], "max_distance": 4},
            {"terms": ["şarj", "tüketiyor"], "max_distance": 4},
            {"terms": ["şarj", "bitiriyor"], "max_distance": 4},
            {"terms": ["fps", "düşüyor"], "max_distance": 4}
        ],
        "regex": [
            r"\b\d+\s*fps\b"
        ],
        "fuzzy": [
            "kasıyor", "kasiyor", "donuyor", "takılıyor", "takiliyor"
        ]
    },

    "crash_hata_bug": {
        "keywords": [
            "bug",
            "hata",
            "hatalı",
            "hata oluştu",
            "hata oluşması",
            "bölümde hata",
            "levelde hata",
            "kendi kendine çıkıyor",
            "kendi kendine kapanıyor",
            "oyundan atıyor",
            "oyundan attı",
            "oyun atıyor",
            "atıyor",
            "kapanıyor",
            "çöküyor",
            "crash",
            "bozuk oyun",
            "dokunmatik algılamıyor",
            "dokunmatik çalışmıyor",
            "tuş yok",
            "buton yok",
            "seçenek yok",
            "ses yok",
            "titreşim yok",
            "hata veriyor",
            "teknik sorun",
            "teknik problem",
            "algılamıyor",
            "basmıyor",
            "tıklanmıyor",
            "çalışmıyor",
            "arızalı",
            "bozulmuş"
        ],
        "near": [
            {"terms": ["oyundan", "atıyor"], "max_distance": 4},
            {"terms": ["oyun", "atıyor"], "max_distance": 4},
            {"terms": ["kendi kendine", "çıkıyor"], "max_distance": 5},
            {"terms": ["kendi kendine", "kapanıyor"], "max_distance": 5},
            {"terms": ["hata", "var"], "max_distance": 4},
            {"terms": ["bug", "var"], "max_distance": 4},
            {"terms": ["dokunmatik", "çalışmıyor"], "max_distance": 5},
            {"terms": ["dokunmatik", "algılamıyor"], "max_distance": 5},
            {"terms": ["tuş", "yok"], "max_distance": 4},
            {"terms": ["buton", "yok"], "max_distance": 4},
            {"terms": ["ses", "yok"], "max_distance": 4},
            {"terms": ["titreşim", "yok"], "max_distance": 4},
            {"terms": ["oyun", "çöküyor"], "max_distance": 4},
            {"terms": ["oyun", "kapanıyor"], "max_distance": 4},
            {"terms": ["teknik", "sorun"], "max_distance": 4}
        ],
        "regex": [],
        "fuzzy": [
            "çöküyor", "kapanıyor", "algılamıyor"
        ]
    },

    "zorluk_level_design": {
        "keywords": [
            "zorlaşıyor",
            "bir bölüm geçmek günlerce sürer mi",
            "bölüm geçmek günlerce sürüyor",
            "günlerce sürüyor",
            "günlerce geçemiyorum",
            "zorlaştırılmış",
            "zorlaştırılmış bölüm",
            "zorlaştır",
            "zorlaştırıyor",
            "zorlaştırdınız",
            "zorlaştırmışsınız",
            "zor yaptınız",
            "çok zor",
            "aşırı zor",
            "fazla zor",
            "gereksiz zor",
            "imkansız",
            "imkânsız",
            "geçemiyorum",
            "geçilmiyor",
            "geçirmiyor",
            "bölüm geçilmiyor",
            "bölümü geçemiyorum",
            "level geçilmiyor",
            "seviye geçilmiyor",
            "ilerleyemiyorum",
            "takıldım",
            "günlerce geçemiyorum",
            "aynı bölüm",
            "hep aynı",
            "aynı leveller",
            "aynı seviyeler",
            "tekrar ediyor",
            "sürekli aynı bölüm",
            "sinir bozucu",
            "sinir krizi",
            "çok kolay",
            "fazla kolay",
            "aşırı kolay",
            "bölümler çok kolay",
            "sorular çok kolay",
            "kolay bölümler zor",
            "zor bölümler kolay",
            "normal bölüm zor",
            "ultra zor",
            "çok sıkıcı",
            "sıkıcı hale geldi",
            "oyundan soğudum",
            "oyun zevki kalmadı",
            "oyun zevkini düşürüyor",
            "strese sokuyor",
            "stres yaptırıyor",
            "bıktırdı",
            "bunalttı",
            "level design"
        ],
        "near": [
            {"terms": ["çok", "zor"], "max_distance": 3},
            {"terms": ["fazla", "zor"], "max_distance": 3},
            {"terms": ["aşırı", "zor"], "max_distance": 3},
            {"terms": ["gereksiz", "zor"], "max_distance": 3},
            {"terms": ["çok", "kolay"], "max_distance": 3},
            {"terms": ["bölüm", "günlerce"], "max_distance": 6},
            {"terms": ["geçmek", "günlerce"], "max_distance": 6},
            {"terms": ["günlerce", "sürüyor"], "max_distance": 5},
            {"terms": ["zorlaştırılmış", "bölüm"], "max_distance": 5},
            {"terms": ["fazla", "kolay"], "max_distance": 3},
            {"terms": ["aşırı", "kolay"], "max_distance": 3},
            {"terms": ["aynı", "bölüm"], "max_distance": 4},
            {"terms": ["aynı", "level"], "max_distance": 4},
            {"terms": ["aynı", "seviye"], "max_distance": 4},
            {"terms": ["hep aynı", "bölüm"], "max_distance": 5},
            {"terms": ["hep aynı", "level"], "max_distance": 5},
            {"terms": ["bölüm", "zor"], "max_distance": 5},
            {"terms": ["level", "zor"], "max_distance": 5},
            {"terms": ["seviye", "zor"], "max_distance": 5},
            {"terms": ["bölüm", "kolay"], "max_distance": 5},
            {"terms": ["level", "kolay"], "max_distance": 5},
            {"terms": ["seviye", "kolay"], "max_distance": 5},
            {"terms": ["bölüm", "tekrar"], "max_distance": 5},
            {"terms": ["level", "tekrar"], "max_distance": 5},
            {"terms": ["sıkıcı", "bölüm"], "max_distance": 5},
            {"terms": ["sinir", "bozucu"], "max_distance": 3},
            {"terms": ["sinir", "krizi"], "max_distance": 3},
            {"terms": ["oyun", "zorlaştı"], "max_distance": 5},
            {"terms": ["bölümler", "zorlaştı"], "max_distance": 5},
            {"terms": ["seviyeler", "zorlaştı"], "max_distance": 5},
            {"terms": ["stres", "oyun"], "max_distance": 6}
        ],
        "regex": [
            r"\b(geçemiyorum|geçilmiyor|ilerleyemiyorum)\b"
        ],
        "fuzzy": [
            "geçemiyorum", "imkansız"
        ]
    },

    "can_hamle_hak_sure": {
        "keywords": [
            "can hakkı",
            "5 can",
            "sınırsız can",
            "can dolma",
            "can dolmuyor",
            "can yetmiyor",
            "can bitti",
            "can az",
            "can yüklenmesi",
            "can yenilenmesi",
            "bekleme süresi",
            "çok bekletiyor",
            "bekleme çok uzun",
            "hamle sayısı",
            "hamle az",
            "hamle yetmiyor",
            "hareketler yetmiyor",
            "hamle bitti",
            "hamle hakkı",
            "hamleleri azalttınız",
            "hamle sayısını düşürdü",
            "hamleleri kısıtlamış",
            "süre sınırı",
            "zaman çok kısa",
            "süre çok kısa",
            "süre yetmiyor",
            "ek süre",
            "15 dakika süre",
            "hak yetmiyor",
            "hak az",
            "her levelde mola",
            "oynatıp bekletiyor",
            "can gelmiyor",
            "can yenilenmiyor",
            "enerji bitiyor",
            "enerji dolmuyor"
        ],
        "near": [
            {"terms": ["can", "dolmuyor"], "max_distance": 4},
            {"terms": ["can", "az"], "max_distance": 4},
            {"terms": ["can", "yetmiyor"], "max_distance": 4},
            {"terms": ["can", "bekleme"], "max_distance": 5},
            {"terms": ["can", "bitti"], "max_distance": 4},
            {"terms": ["can", "yenilenmiyor"], "max_distance": 4},
            {"terms": ["hamle", "az"], "max_distance": 4},
            {"terms": ["hamle", "yetmiyor"], "max_distance": 4},
            {"terms": ["hamle", "sayısı"], "max_distance": 4},
            {"terms": ["hamle", "bitti"], "max_distance": 4},
            {"terms": ["hamle", "kısıt"], "max_distance": 5},
            {"terms": ["hamle", "düşürdü"], "max_distance": 5},
            {"terms": ["süre", "az"], "max_distance": 4},
            {"terms": ["süre", "kısa"], "max_distance": 4},
            {"terms": ["süre", "yetmiyor"], "max_distance": 4},
            {"terms": ["süre", "bitti"], "max_distance": 4},
            {"terms": ["zaman", "çok kısa"], "max_distance": 4},
            {"terms": ["hak", "az"], "max_distance": 4},
            {"terms": ["hak", "yetmiyor"], "max_distance": 4},
            {"terms": ["hak", "bitti"], "max_distance": 4},
            {"terms": ["enerji", "dolmuyor"], "max_distance": 4}
        ],
        "regex": [],
        "fuzzy": []
    },

    "odeme_satin_alma_ekonomi": {
        "keywords": [
            "satın alma",
            "kumara döndü",
            "kumar gibi",
            "oyun kumara döndü",
            "kumar oyunu gibi",
            "paralı kumar gibi",
            "satın almaya",
            "satın alım",
            "satın alımlar",
            "oyun içi satın alma",
            "para yoksa oyun yok",
            "her şey parayla",
            "herşey parayla",
            "para yatırmaya zorluyor",
            "para kaptırmak",
            "para kaptırmam",
            "para istemiyor",
            "para istiyor",
            "cebinizdeki para",
            "para dayanıklı",
            "para ile aldırıyor",
            "para ile can",
            "can satın alalım",
            "altın aldırıyor",
            "ücretlendirme",
            "ücretli",
            "pahalı",
            "çok pahalı",
            "aşırı pahalı",
            "fazla pahalı",
            "ticarethane",
            "kredi kartı",
            "ödeme yap",
            "ödeme yaptım",
            "para iadesi",
            "iade",
            "geri ödeme",
            "premium",
            "ücret ödemeden",
            "para çekildi",
            "param boşa gitti",
            "param gitti",
            "paramı aldı",
            "para tuzağı",
            "para harcatıyor",
            "para harcamaya zorluyor",
            "para harcamaya sürülüyor",
            "para harcamak zorunda",
            "para yüklemen için",
            "para yükletiyor",
            "altın almaya zorluyor",
            "altın almak zorunda",
            "coin almaya zorluyor",
            "jeton almaya zorluyor",
            "satın almaya zorluyor",
            "almaya zorluyor",
            "paralı oyuna döndü",
            "paralı oyuna çevirdiniz",
            "oyun tamamen para",
            "oyun para istiyor",
            "oyun paraya döndü",
            "oyun paraya çevrilmiş",
            "paraya endeksli",
            "tek derdiniz para",
            "amaç para",
            "amaç para harcatmak",
            "amaç altın aldırmak",
            "para kasmak",
            "para kazanmak için",
            "cebinize çalışıyor",
            "parayla geçiliyor",
            "parasız ilerlenmiyor",
            "parasız geçilmiyor",
            "bedava oynanmıyor",
            "pay to win",
            "p2w",
            "paket almadan geçilmiyor",
            "paket almaya zorluyor",
            "fiyat çok yüksek",
            "fiyatlar arttı",
            "ürünlerin fiyatı yükseldi",
            "altın fiyatı yüksek",
            "coin pahalı",
            "jeton pahalı",
            "çip pahalı",
            "tl istiyor",
            "para yatırmadan olmuyor"
        ],
        "near": [
            {"terms": ["para", "verdim"], "max_distance": 5},
            {"terms": ["kumar", "döndü"], "max_distance": 5},
            {"terms": ["kumar", "gibi"], "max_distance": 5},
            {"terms": ["oyun", "kumar"], "max_distance": 6},
            {"terms": ["para", "çekildi"], "max_distance": 5},
            {"terms": ["para", "iade"], "max_distance": 5},
            {"terms": ["para", "gelmedi"], "max_distance": 5},
            {"terms": ["para", "aldı"], "max_distance": 5},
            {"terms": ["para", "harca"], "max_distance": 6},
            {"terms": ["para", "harcat"], "max_distance": 6},
            {"terms": ["para", "zorluyor"], "max_distance": 6},
            {"terms": ["para", "tuzağı"], "max_distance": 4},
            {"terms": ["satın", "aldım"], "max_distance": 4},
            {"terms": ["satın", "alma"], "max_distance": 4},
            {"terms": ["satın", "almaya"], "max_distance": 4},
            {"terms": ["satın alma", "zorluyor"], "max_distance": 6},
            {"terms": ["almaya", "zorluyor"], "max_distance": 4},
            {"terms": ["altın", "al"], "max_distance": 6},
            {"terms": ["altın", "pahalı"], "max_distance": 5},
            {"terms": ["coin", "az"], "max_distance": 5},
            {"terms": ["coin", "gelmedi"], "max_distance": 5},
            {"terms": ["coin", "pahalı"], "max_distance": 5},
            {"terms": ["coin", "yetmiyor"], "max_distance": 5},
            {"terms": ["altın", "az"], "max_distance": 5},
            {"terms": ["altın", "gelmedi"], "max_distance": 5},
            {"terms": ["jeton", "az"], "max_distance": 5},
            {"terms": ["jeton", "pahalı"], "max_distance": 5},
            {"terms": ["oyun", "paralı"], "max_distance": 5},
            {"terms": ["oyun", "para"], "max_distance": 6},
            {"terms": ["parasız", "ilerlenmiyor"], "max_distance": 5},
            {"terms": ["parasız", "geçilmiyor"], "max_distance": 5},
            {"terms": ["paket", "almadan"], "max_distance": 5}
        ],
        "regex": [
            r"\bkredi kartı\b",
            r"\bpremium\b",
            r"\bpay\s*to\s*win\b",
            r"\bp2w\b"
        ],
        "fuzzy": [
            "premium", "iade"
        ]
    },

    "odul_bonus_ipucu": {
        "keywords": [
            "bonus",
            "ödül",
            "ödül vermedi",
            "ödülü vermedi",
            "kazandığım ödülü vermedi",
            "kazandığım vermedi",
            "bonus vermedi",
            "hediye vermedi",
            "altın vermedi",
            "puan vermedi",
            "ödüller",
            "ödülleri azalttılar",
            "ödüller azaldı",
            "ödüller çok az",
            "ödül az",
            "ödül vermiyor",
            "ödül gelmedi",
            "ödülleri kıstınız",
            "ödülleri düşürdünüz",
            "hediye",
            "hediyeler",
            "hediyeleri azalttılar",
            "hediye azaldı",
            "hediye gelmiyor",
            "hediye vermiyor",
            "sandık",
            "çark",
            "güçlendirici",
            "booster",
            "ışık top",
            "roket",
            "bomba",
            "tokmak",
            "yay",
            "kazandıklarını vermedi",
            "kazandığım gelmedi",
            "verdiği ödül az",
            "ipucu",
            "ampul",
            "joker",
            "altın vermiyor",
            "altın az veriyor",
            "puan az",
            "puan vermiyor",
            "puan gelmedi",
            "kazanınca az veriyor",
            "kaybedince çok alıyor",
            "kart vermiyor",
            "kart gelmiyor",
            "kart çıkmıyor",
            "yeni kart çıkmadı",
            "aynı kart çıkıyor",
            "kart düşmüyor",
            "altın kart vermiyor",
            "koleksiyon tamamlanmıyor",
            "koleksiyonu tamamlatmıyor",
            "gerekli kartı vermiyor"
        ],
        "near": [
            {"terms": ["ödül", "vermiyor"], "max_distance": 5},
            {"terms": ["ödül", "az"], "max_distance": 5},
            {"terms": ["ödül", "gelmedi"], "max_distance": 5},
            {"terms": ["ödül", "alamadım"], "max_distance": 5},
            {"terms": ["ödül", "vermedi"], "max_distance": 5},
            {"terms": ["bonus", "vermedi"], "max_distance": 5},
            {"terms": ["hediye", "vermedi"], "max_distance": 5},
            {"terms": ["altın", "vermedi"], "max_distance": 5},
            {"terms": ["puan", "vermedi"], "max_distance": 5},
            {"terms": ["ödüller", "azaldı"], "max_distance": 5},
            {"terms": ["ödülleri", "düşürdünüz"], "max_distance": 5},
            {"terms": ["ödülleri", "kıstınız"], "max_distance": 5},
            {"terms": ["bonus", "vermiyor"], "max_distance": 5},
            {"terms": ["bonus", "az"], "max_distance": 5},
            {"terms": ["hediye", "vermiyor"], "max_distance": 5},
            {"terms": ["hediye", "az"], "max_distance": 5},
            {"terms": ["hediye", "gelmedi"], "max_distance": 5},
            {"terms": ["hediyeleri", "azalttılar"], "max_distance": 5},
            {"terms": ["kazandıklarını", "vermedi"], "max_distance": 5},
            {"terms": ["kart", "vermiyor"], "max_distance": 5},
            {"terms": ["kart", "gelmiyor"], "max_distance": 5},
            {"terms": ["kart", "çıkmıyor"], "max_distance": 5},
            {"terms": ["kart", "düşmüyor"], "max_distance": 5},
            {"terms": ["altın", "vermiyor"], "max_distance": 5},
            {"terms": ["altın", "az"], "max_distance": 5},
            {"terms": ["puan", "az"], "max_distance": 5},
            {"terms": ["puan", "vermiyor"], "max_distance": 5}
        ],
        "regex": [
            r"\b(sandık|çark|joker|ipucu|ampul|bonus|booster)\b"
        ],
        "fuzzy": [
            "joker", "ipucu"
        ]
    },

    "kart_koleksiyon": {
        "keywords": [
            "mor kart",
            "sarı kart",
            "gümüş kart",
            "altın kart",
            "kart vermedi",
            "kartı vermedi",
            "kartları vermedi",
            "son kartı vermedi",
            "eksik kartı vermedi",
            "eksik kart",
            "kart isteği",
            "kart paketi",
            "kart paketi gözükmüyor",
            "kartları vermiyor",
            "eksik kartı vermiyor",
            "kart açmama rağmen",
            "kartlar çıkmıyor",
            "aynı kart",
            "kart çıkmıyor",
            "kart gelmiyor",
            "kart vermiyor",
            "kart düşmüyor",
            "yeni kart çıkmadı",
            "koleksiyon",
            "koleksiyon tamamlanmıyor",
            "koleksiyonu tamamlayamıyorum",
            "koleksiyonu tamamlatmıyor",
            "kartları topluyoruz",
            "tek kart kaldı",
            "iki kart kaldı",
            "son kartı vermiyor",
            "gerekli kartı vermiyor",
            "hep aynı kart",
            "kartlar eksik",
            "kart sistemi",
            "kart etkinliği",
            "kart albümü"
        ],
        "near": [
            {"terms": ["kart", "çıkmıyor"], "max_distance": 5},
            {"terms": ["kart", "eksik"], "max_distance": 5},
            {"terms": ["kart", "aynı"], "max_distance": 5},
            {"terms": ["kart", "gelmiyor"], "max_distance": 5},
            {"terms": ["kart", "vermiyor"], "max_distance": 5},
            {"terms": ["kart", "düşmüyor"], "max_distance": 5},
            {"terms": ["mor", "kart"], "max_distance": 3},
            {"terms": ["sarı", "kart"], "max_distance": 3},
            {"terms": ["gümüş", "kart"], "max_distance": 3},
            {"terms": ["altın", "kart"], "max_distance": 3},
            {"terms": ["kart", "vermedi"], "max_distance": 5},
            {"terms": ["son", "kart", "vermedi"], "max_distance": 6},
            {"terms": ["eksik", "kart", "vermedi"], "max_distance": 6},
            {"terms": ["koleksiyon", "eksik"], "max_distance": 5},
            {"terms": ["koleksiyon", "tamamlanmıyor"], "max_distance": 5},
            {"terms": ["tek", "kart"], "max_distance": 5},
            {"terms": ["son", "kart"], "max_distance": 5}
        ],
        "regex": [],
        "fuzzy": []
    },

    "hile_algoritma_adalet": {
        "keywords": [
            "hile",
            "algoritma",
            "kasıtlı",
            "hileli",
            "oyun hileli",
            "hileli oyun",
            "hileli oynanabiliyor",
            "oyun hileli oynanabiliyor",
            "sistem hileli",
            "bilerek",
            "rastgele değil",
            "oyun isterse",
            "oyun seni yönetiyor",
            "kaybettiriyor",
            "kurmaca",
            "kurgulu",
            "ayarlanmış",
            "adaletsiz",
            "haksızlık",
            "sahtekarlık",
            "izin vermiyor",
            "oynatmıyor",
            "kafana göre",
            "geçme ihtimali yok",
            "kaybeden ben oluyorum",
            "puanlarım gelmiyor",
            "oyun bizimle oynuyor",
            "sistem engelliyor",
            "sistem izin vermiyor",
            "sistem geçirmiyor",
            "bilerek geçirmiyor",
            "bilerek kaybettiriyor",
            "hamleleri engelliyor",
            "hamleleri bozuyor",
            "farklı hamle yaptırıyor",
            "oyun müdahale ediyor",
            "taşlara müdahale ediyor",
            "düzene müdahale ediyor",
            "ekstra vermiyor",
            "güçlendirici vermiyor",
            "oyun geçirtmiyor",
            "oyun bilerek zorlaştırıyor",
            "sistemin insafına göre",
            "canı ne isterse oluyor",
            "çifte standart",
            "herkese aynı gelmiyor",
            "seçmece kişilere geliyor",
            "oyuncuya göre değişiyor",
            "denge yok",
            "adil değil",
            "oyun adil değil",
            "hak yemişsiniz",
            "emeğim boşa gitti",
            "boşuna emek",
            "algoritması arızalı",
            "oyun ayarlı",
            "oyun kurulmuş",
            "sistem kurulmuş"
        ],
        "near": [
            {"terms": ["oyun", "kaybettiriyor"], "max_distance": 5},
            {"terms": ["oyun", "yönetiyor"], "max_distance": 5},
            {"terms": ["oyun", "izin vermiyor"], "max_distance": 6},
            {"terms": ["oyun", "oynatmıyor"], "max_distance": 5},
            {"terms": ["oyun", "geçirtmiyor"], "max_distance": 5},
            {"terms": ["oyun", "müdahale"], "max_distance": 6},
            {"terms": ["oyun", "hileli"], "max_distance": 5},
            {"terms": ["hileli", "oynanabiliyor"], "max_distance": 5},
            {"terms": ["sistem", "hileli"], "max_distance": 5},
            {"terms": ["bilerek", "kaybettiriyor"], "max_distance": 5},
            {"terms": ["bilerek", "vermiyor"], "max_distance": 5},
            {"terms": ["bilerek", "geçirmiyor"], "max_distance": 5},
            {"terms": ["hamle", "engelliyor"], "max_distance": 5},
            {"terms": ["hamle", "bozuyor"], "max_distance": 5},
            {"terms": ["hamle", "yaptırıyor"], "max_distance": 6},
            {"terms": ["sistem", "engelliyor"], "max_distance": 5},
            {"terms": ["sistem", "geçirmiyor"], "max_distance": 5},
            {"terms": ["sistem", "izin vermiyor"], "max_distance": 6},
            {"terms": ["algoritma", "arızalı"], "max_distance": 5},
            {"terms": ["adil", "değil"], "max_distance": 4},
            {"terms": ["çifte", "standart"], "max_distance": 4},
            {"terms": ["herkese", "aynı"], "max_distance": 6}
        ],
        "regex": [
            r"\b(hile|algoritma|sahtekarlık|haksızlık|adaletsiz)\b",
            r"\bkafana göre\b",
            r"\bhileli\b",
            r"\brastgele değil\b"
        ],
        "fuzzy": [
            "adaletsiz", "haksızlık", "sahtekarlık"
        ]
    },

    "destek_iletisim": {
        "keywords": [
            "yardımcı olur musunuz",
            "yardım edin",
            "yardım istiyorum",
            "iletişime geçemiyorum",
            "sorun bildire ulaşılmıyor",
            "destek ekibi ile irtibat",
            "desteğe bağlanamadım",
            "yardımcı olurmusunuz",
            "yardımcı olur musunuz",
            "cevap vermiyor",
            "cevap alamadım",
            "geri dönüş",
            "geri dönüş yok",
            "geri dönüş yapılmadı",
            "sorun bildir",
            "dikkate alınırsa",
            "çözümü nedir",
            "çözüm bulur musunuz",
            "çözüm bulun",
            "düzeltebilir miyiz",
            "müşteri temsilcisi",
            "ulaşamıyorum",
            "ilgilenmiyor",
            "hala ilgilenmiyorsunuz",
            "açıklama yapın",
            "muhatap yok",
            "muhatap bulamıyorum",
            "destek yok",
            "destek vermiyor",
            "destek bölümü yok",
            "yardım kısmı yok",
            "yardım kısmından yazamıyorum",
            "yardıma yazılmıyor",
            "teknik destek",
            "şikayetimi yazdım",
            "cevap yazın",
            "okuyup cevap yazın",
            "lütfen bakın",
            "neden cevap vermiyorsunuz",
            "sorumlu yok",
            "kimse ilgilenmiyor",
            "konunun düzeltilmesini istiyorum",
            "inceleme yapılmasını istiyorum"
        ],
        "near": [
            {"terms": ["destek", "lütfen"], "max_distance": 6},
            {"terms": ["destek", "istiyorum"], "max_distance": 6},
            {"terms": ["destek", "bekliyorum"], "max_distance": 6},
            {"terms": ["destek", "yok"], "max_distance": 5},
            {"terms": ["yardım", "lütfen"], "max_distance": 6},
            {"terms": ["yardım", "istiyorum"], "max_distance": 6},
            {"terms": ["yardım", "edin"], "max_distance": 4},
            {"terms": ["müşteri temsilcisi", "bekliyorum"], "max_distance": 6},
            {"terms": ["cevap", "vermiyor"], "max_distance": 4},
            {"terms": ["cevap", "alamadım"], "max_distance": 4},
            {"terms": ["geri dönüş", "yok"], "max_distance": 5},
            {"terms": ["geri dönüş", "yapılmadı"], "max_distance": 5},
            {"terms": ["geri dönüş", "vermiyor"], "max_distance": 5},
            {"terms": ["iletişime", "geçemiyorum"], "max_distance": 4},
            {"terms": ["çözümü", "nedir"], "max_distance": 4},
            {"terms": ["yardım", "yazılmıyor"], "max_distance": 5},
            {"terms": ["şikayet", "cevap"], "max_distance": 7}
        ],
        "regex": [],
        "fuzzy": [
            "ulaşamıyorum"
        ]
    },

    "sohbet_takim_arkadas_topluluk": {
        "keywords": [
            "sohbet",
            "mesaj",
            "chat",
            "kart isteği görünmüyor",
            "isteği arkadaşlar göremiyor",
            "takımı kimse katılmıyor",
            "ban",
            "erişim engeli",
            "spam engeli",
            "takım",
            "grup",
            "kulüp",
            "lider",
            "arkadaşlarımı göremiyorum",
            "arkadaş listem",
            "arkadaş ekleyemiyorum",
            "arkadaş gönderemiyorum",
            "puanlarını göremiyoruz",
            "istek gönderemiyorum",
            "konuşamıyorum",
            "küfür",
            "hakaret",
            "oyuncu davet",
            "takımdan çıkardım",
            "takımıma alamıyorum",
            "takıma giremiyorum",
            "takıma katılamıyorum",
            "takımdan attı",
            "takımım dağıldı",
            "takım arkadaşları",
            "haftalık yarış",
            "takım sandığı",
            "takım puanı",
            "takım lideri",
            "mesajlar silinmiyor",
            "sohbet çalışmıyor"
        ],
        "near": [
            {"terms": ["arkadaş", "göremiyorum"], "max_distance": 5},
            {"terms": ["arkadaş", "listem"], "max_distance": 5},
            {"terms": ["arkadaş", "ekleyemiyorum"], "max_distance": 5},
            {"terms": ["takım", "alamıyorum"], "max_distance": 5},
            {"terms": ["takım", "çıkardım"], "max_distance": 5},
            {"terms": ["takım", "giremiyorum"], "max_distance": 5},
            {"terms": ["mesaj", "silinmiyor"], "max_distance": 5}
        ],
        "regex": [
            r"\b(sohbet|chat|mesaj|takım|grup|kulüp)\b",
            r"\b(ban|erişim engeli|spam engeli)\b",
            r"\b(küfür|hakaret)\b"
        ],
        "fuzzy": []
    },

    "hesap_kayit_ilerleme": {
        "keywords": [
            "hesabım",
            "hesap",
            "hesabım gitti",
            "hesabım silindi",
            "hesabım sıfırlandı",
            "hesabımı bulamıyorum",
            "facebook",
            "ilerleme yapamıyor",
            "ilerleme kaydedemiyorum",
            "ilerleme kaydedemiyor",
            "oyuna baştan başlıyım",
            "hesabımı silmeye çalışıyorum",
            "yeniden başladı",
            "google play",
            "baştan başladı",
            "sıfırdan başladı",
            "sıfırlandı",
            "oyun sıfırlandı",
            "kaldığım yerden",
            "ilerlemem kayboldu",
            "ilerlemem gitti",
            "ilerleme kayboldu",
            "ilerleme silindi",
            "telefonuma aktardım",
            "telefon değişikliği",
            "telefon değişti",
            "cihaz değişikliği",
            "format",
            "oyunu silmek istiyorum",
            "yeniden başlattı",
            "levelimi geri alamadım",
            "seviyem gitti",
            "levelim gitti",
            "oyunum silindi",
            "isim değiştirme",
            "kullanıcı adı değiştirme",
            "kullanıcı adımı değiştiremiyorum",
            "1 seviyeye düştüm",
            "geri attı",
            "geriye dönüyor",
            "sıfırlanma",
            "koleksiyon yeniden başladı",
            "oyuna yeniden başladı",
            "eski hesabımı istiyorum",
            "hesap bağlanmıyor",
            "hesaba giriş yapamıyorum",
            "verilerim gitti"
        ],
        "near": [
            {"terms": ["hesab", "silindi"], "max_distance": 5},
            {"terms": ["hesab", "gitti"], "max_distance": 5},
            {"terms": ["hesab", "geri alamadım"], "max_distance": 6},
            {"terms": ["hesab", "sıfırlandı"], "max_distance": 5},
            {"terms": ["baştan", "başladı"], "max_distance": 5},
            {"terms": ["sıfırdan", "başladı"], "max_distance": 5},
            {"terms": ["level", "geri alamadım"], "max_distance": 6},
            {"terms": ["telefon", "değişti"], "max_distance": 5},
            {"terms": ["facebook", "bağlan"], "max_distance": 6},
            {"terms": ["facebook", "giriş"], "max_distance": 6},
            {"terms": ["google play", "bağlan"], "max_distance": 6},
            {"terms": ["google play", "giriş"], "max_distance": 6},
            {"terms": ["ilerleme", "gitti"], "max_distance": 5},
            {"terms": ["ilerleme", "silindi"], "max_distance": 5},
            {"terms": ["ilerleme", "kayboldu"], "max_distance": 5},
            {"terms": ["kullanıcı adı", "değiştirme"], "max_distance": 6},
            {"terms": ["oyun", "sıfırlandı"], "max_distance": 5}
        ],
        "regex": [],
        "fuzzy": [
            "sıfırlandı"
        ]
    },

    "internet_cevrimdisi": {
        "keywords": [
            "internetsiz",
            "çevrimdışı",
            "çevrim dışı",
            "internet yokken",
            "internet kapalıyken",
            "internet bağlantısız",
            "internet olmadan oynanmıyor",
            "internetsiz oynanmıyor",
            "internetsiz oynayamıyoruz",
            "internet istiyor",
            "internet istemesin",
            "internet bağlantısı yok",
            "bağlantı hatası",
            "wifi yok",
            "wifi çekmiyor",
            "wifi bağlanmıyor",
            "uçak modunda",
            "interneti kapatınca",
            "internet açınca",
            "offline",
            "online istiyor",
            "bağlantısız oynansın"
        ],
        "near": [
            {"terms": ["internet", "yok"], "max_distance": 5},
            {"terms": ["internet", "olmadan"], "max_distance": 5},
            {"terms": ["internet", "kapalı"], "max_distance": 5},
            {"terms": ["internet", "çekmiyor"], "max_distance": 5},
            {"terms": ["internet", "istemesin"], "max_distance": 5},
            {"terms": ["internet", "bağlantı"], "max_distance": 5},
            {"terms": ["internetsiz", "oynanmıyor"], "max_distance": 5},
            {"terms": ["internetsiz", "oynayamıyorum"], "max_distance": 5},
            {"terms": ["wifi", "yok"], "max_distance": 5},
            {"terms": ["wifi", "bağlanmıyor"], "max_distance": 5},
            {"terms": ["wifi", "çekmiyor"], "max_distance": 5},
            {"terms": ["interneti", "kapatınca"], "max_distance": 5}
        ],
        "regex": [
            r"\bçevrim\s*dışı\b"
        ],
        "fuzzy": [
            "internetsiz", "çevrimdışı"
        ]
    },

    "gizlilik_guvenlik_izin": {
        "keywords": [
            "gizlilik",
            "sözleşme",
            "kullanım koşulları",
            "kabul etmek zorundayım",
            "kişisel bilgiler",
            "kişisel veri",
            "verilerimi istiyor",
            "rehber",
            "e posta",
            "ajanlık",
            "casusluk",
            "izin onay",
            "izin istiyor",
            "gereksiz izin",
            "bildirim izni",
            "kamera izni",
            "konum izni",
            "mikrofon izni",
            "güvenli değil",
            "kimlik",
            "finansal bilgiler",
            "kart bilgilerim",
            "güvenlik sorunu",
            "şüpheli",
            "hesap güvenliği",
            "veri topluyor"
        ],
        "near": [
            {"terms": ["kişisel", "bilgi"], "max_distance": 5},
            {"terms": ["kişisel", "veri"], "max_distance": 5},
            {"terms": ["finansal", "bilgi"], "max_distance": 5},
            {"terms": ["rehber", "izin"], "max_distance": 5},
            {"terms": ["kimlik", "izin"], "max_distance": 5},
            {"terms": ["e posta", "izin"], "max_distance": 5},
            {"terms": ["kamera", "izin"], "max_distance": 5},
            {"terms": ["konum", "izin"], "max_distance": 5}
        ],
        "regex": [
            r"\b(gizlilik|sözleşme|kullanım koşulları)\b",
            r"\bgüvenli değil\b"
        ],
        "fuzzy": []
    },

    "dil_lokalizasyon": {
        "keywords": [
            "türkçe değil",
            "türkçe yok",
            "türkçe olmuyor",
            "türkçeye çevrilmemiş",
            "türkçe dil yok",
            "türkçe destek yok",
            "dil desteği",
            "dil sorunu",
            "dil değişmiyor",
            "dil seçeneği yok",
            "ingilizceye geçiyor",
            "ingilizce oldu",
            "ingilizce kaldı",
            "yarı ingilizce",
            "sorular ingilizce",
            "çeviri kötü",
            "çeviri hatalı",
            "çeviri yok",
            "yanlış çeviri",
            "anlaşılmıyor",
            "dil bozuk",
            "Türkçe karakter sorunu",
            "metinler bozuk",
            "yazılar ingilizce",
            "menü ingilizce"
        ],
        "near": [
            {"terms": ["türkçe", "değil"], "max_distance": 4},
            {"terms": ["türkçe", "olmuyor"], "max_distance": 4},
            {"terms": ["türkçe", "yok"], "max_distance": 4},
            {"terms": ["ingilizce", "geçiyor"], "max_distance": 5},
            {"terms": ["ingilizce", "sorular"], "max_distance": 5},
            {"terms": ["ingilizce", "oluyor"], "max_distance": 5},
            {"terms": ["ingilizce", "kaldı"], "max_distance": 5},
            {"terms": ["dil", "desteği"], "max_distance": 5},
            {"terms": ["dil", "sorunu"], "max_distance": 5},
            {"terms": ["dil", "yok"], "max_distance": 5},
            {"terms": ["dil", "değişmiyor"], "max_distance": 5},
            {"terms": ["çeviri", "kötü"], "max_distance": 5},
            {"terms": ["çeviri", "hatalı"], "max_distance": 5},
            {"terms": ["çeviri", "yok"], "max_distance": 5},
            {"terms": ["menü", "ingilizce"], "max_distance": 5}
        ],
        "regex": [],
        "fuzzy": []
    },

    "uygunsuz_icerik_yas": {
        "keywords": [
            "çocuklar için uygun değil",
            "küçük çocuklar",
            "çocuklara uygun değil",
            "çocuklara kötü",
            "yaş sınırı",
            "uygunsuz",
            "cinsel",
            "+18",
            "18 yaş",
            "sapık",
            "kötü örnek",
            "şiddet",
            "aldatma",
            "küfürlü",
            "argo",
            "çocuk oyunu değil",
            "çocuklar oynamasın",
            "aile için uygun değil",
            "reklamlar uygunsuz",
            "uygunsuz reklam",
            "korkutucu",
            "rahatsız edici içerik"
        ],
        "near": [
            {"terms": ["çocuk", "uygun değil"], "max_distance": 6},
            {"terms": ["çocuk", "kötü"], "max_distance": 6},
            {"terms": ["reklam", "uygunsuz"], "max_distance": 5},
            {"terms": ["uygunsuz", "reklam"], "max_distance": 5}
        ],
        "regex": [
            r"\b(yaş sınırı|uygunsuz|cinsel|şiddet|aldatma)\b",
            r"\bkötü örnek\b",
            r"\+18\b"
        ],
        "fuzzy": []
    },

    "egitici_bilissel_fayda": {
        "keywords": [
            "beyin geliştirme",
            "beynimi çalıştırıyor",
            "beyin çalıştırıyor",
            "beyin egzersizi",
            "zekayı geliştiriyor",
            "zeka geliştiriyor",
            "zihin geliştiriyor",
            "zihni açıyor",
            "düşündürür",
            "düşündürüyor",
            "mantık geliştiriyor",
            "mantık oyunu",
            "kelime haznesi",
            "kelime öğren",
            "bilgi artırıyor",
            "bilgim artıyor",
            "bilgi ve beceri",
            "karar verme",
            "eğitici",
            "öğretici",
            "hafıza",
            "hafızayı güçlendiriyor",
            "bulmaca",
            "zeka oyunu",
            "akıl oyunu",
            "çocuklar için eğitici",
            "öğrenmeye yardımcı",
            "zeka açıcı",
            "pratik yaptırıyor"
        ],
        "near": [
            {"terms": ["beyin", "geliştir"], "max_distance": 5},
            {"terms": ["zeka", "geliştir"], "max_distance": 5},
            {"terms": ["zihin", "geliştir"], "max_distance": 5},
            {"terms": ["hafıza", "geliştir"], "max_distance": 5},
            {"terms": ["kelime", "öğren"], "max_distance": 5},
            {"terms": ["kelime", "haznesi"], "max_distance": 5},
            {"terms": ["bilgi", "artıyor"], "max_distance": 5},
            {"terms": ["bilgi", "beceri"], "max_distance": 5},
            {"terms": ["mantık", "geliştir"], "max_distance": 5}
        ],
        "regex": [
            r"\b(eğitici|öğretici|mantık oyunu|bulmaca|zeka oyunu|akıl oyunu)\b"
        ],
        "fuzzy": []
    },

    "olumlu_deneyim": {
        "keywords": [
            "çok güzel",
            "güzel oyun",
            "harika",
            "mükemmel",
            "muhteşem",
            "süper",
            "efsane",
            "şahane",
            "keyifli",
            "eğlenceli",
            "çok eğlenceli",
            "çok keyifli",
            "sürükleyici",
            "rahatlatıcı",
            "bağımlılık",
            "bağımlısı",
            "tavsiye ederim",
            "öneririm",
            "herkese öneririm",
            "herkese tavsiye ederim",
            "beğendim",
            "çok beğendim",
            "bayıldım",
            "sevdim",
            "çok sevdim",
            "severek oynuyorum",
            "kafa dağıtmak",
            "kafa dağıtıyor",
            "stres at",
            "stres atmak için",
            "başarılı",
            "çok başarılı",
            "on numara",
            "10 numara",
            "kaliteli",
            "zevkli",
            "sarıyor",
            "çok iyi",
            "gayet iyi",
            "gayet güzel",
            "müq",
            "mük",
            "perfect",
            "excellent",
            "iyi oyun",
            "ellerinize sağlık",
            "elinize sağlık",
            "favori oyunum",
            "favorim",
            "çok hoş",
            "güzel vakit geçiriyorum",
            "zaman geçirmek için güzel",
            "boş zaman için güzel",
            "oynaması güzel",
            "oyun güzel",
            "oyun iyi",
            "emeğinize sağlık",
            "teşekkürler",
            "yapanların eline sağlık",
            "başarılar",
            "hak ediyor",
            "5 yıldız hak ediyor",
            "beş yıldız hak ediyor"
        ],
        "near": [
            {"terms": ["çok", "güzel"], "max_distance": 3},
            {"terms": ["çok", "iyi"], "max_distance": 3},
            {"terms": ["çok", "harika"], "max_distance": 3},
            {"terms": ["çok", "mükemmel"], "max_distance": 3},
            {"terms": ["çok", "süper"], "max_distance": 3},
            {"terms": ["aşırı", "güzel"], "max_distance": 3},
            {"terms": ["aşırı", "iyi"], "max_distance": 3},
            {"terms": ["aşırı", "harika"], "max_distance": 3},
            {"terms": ["aşırı", "mükemmel"], "max_distance": 3},
            {"terms": ["aşırı", "süper"], "max_distance": 3},
            {"terms": ["gayet", "güzel"], "max_distance": 3},
            {"terms": ["gayet", "iyi"], "max_distance": 3},
            {"terms": ["tavsiye", "ederim"], "max_distance": 4},
            {"terms": ["tavsiye", "ediyorum"], "max_distance": 4},
            {"terms": ["severek", "oynuyorum"], "max_distance": 4},
            {"terms": ["ellerinize", "sağlık"], "max_distance": 4},
            {"terms": ["eline", "sağlık"], "max_distance": 4},
            {"terms": ["oyun", "güzel"], "max_distance": 4},
            {"terms": ["oyun", "iyi"], "max_distance": 4}
        ],
        "regex": [
            r"\b(beğendim|bayıldım|efsane|şahane)\b"
        ],
        "fuzzy": [
            "güzel", "guzel", "harika", "mükemmel", "mukemmel", "efsane"
        ]
    },

    "genel_negatif_deneyim": {
        "keywords": [
            "berbat",
            "rezalet",
            "çok kötü",
            "aşırı kötü",
            "kabus",
            "adilik",
            "hak etmiyorsunuz",
            "bu puanı hak etmiyorsunuz",
            "saçma olmuş",
            "oyun mahvolmuş",
            "oyunu mahvettiniz",
            "çok saçma",
            "soğuttunuz",
            "oyundan soğuttunuz",
            "oynamaya değmez",
            "değer mi sanmıyorum",
            "kanser olmak isteyen yüklesin",
            "salakça",
            "tiskinmeye başladım",
            "saçma",
            "saçmalık",
            "saçmalamış",
            "saçmaladı",
            "beğenmedim",
            "hiç iyi değil",
            "boş oyun",
            "bomboş oyun",
            "zaman kaybı",
            "vakit kaybı",
            "boşa vakit",
            "sildim",
            "sileceğim",
            "silicem",
            "kaldırıyorum",
            "kaldırdım",
            "oynamayın",
            "indirmeyin",
            "yüklemeyin",
            "tavsiye etmiyorum",
            "tavsiye etmem",
            "nefret",
            "lanet",
            "çekilmez",
            "oynayası gelmiyor",
            "benlik değil",
            "sarmıyor",
            "bomboş bir oyun",
            "zamanınıza yazık",
            "emeğime yazık",
            "5 kuruş etmiyor",
            "yüklemeye değmez",
            "başarısız",
            "siz oyun yapmayın",
            "kıymetsiz",
            "gereksiz",
            "çöp",
            "kötü oyun",
            "oyun kötü",
            "rezilleşti",
            "kötüleşti",
            "mahvoldu",
            "oyunun içine ettiniz",
            "sinir oyunu",
            "sinir hastası eder",
            "sinir bozuyor",
            "oyundan soğudum",
            "keyif vermiyor",
            "keyif almıyorum",
            "eğlencesi kalmadı",
            "zevki kalmadı",
            "artık sıktı",
            "artık sıkıldım",
            "bıktım",
            "bunaldım",
            "işkence gibi",
            "eziyete dönüştü",
            "stres yapıyor",
            "strese sokuyor",
            "moral bozuyor",
            "pişman oldum",
            "hayal kırıklığı"
        ],
        "near": [
            {"terms": ["çok", "kötü"], "max_distance": 3},
            {"terms": ["çok", "berbat"], "max_distance": 3},
            {"terms": ["çok", "rezalet"], "max_distance": 3},
            {"terms": ["çok", "saçma"], "max_distance": 3},
            {"terms": ["hak", "etmiyorsunuz"], "max_distance": 4},
            {"terms": ["oyun", "mahvolmuş"], "max_distance": 5},
            {"terms": ["oyunu", "mahvettiniz"], "max_distance": 5},
            {"terms": ["aşırı", "kötü"], "max_distance": 3},
            {"terms": ["aşırı", "berbat"], "max_distance": 3},
            {"terms": ["aşırı", "rezalet"], "max_distance": 3},
            {"terms": ["aşırı", "saçma"], "max_distance": 3},
            {"terms": ["fazla", "kötü"], "max_distance": 3},
            {"terms": ["fazla", "saçma"], "max_distance": 3},
            {"terms": ["zaman", "kaybı"], "max_distance": 4},
            {"terms": ["vakit", "kaybı"], "max_distance": 4},
            {"terms": ["tavsiye", "etmiyorum"], "max_distance": 4},
            {"terms": ["tavsiye", "etmem"], "max_distance": 4},
            {"terms": ["oyun", "kötüleşti"], "max_distance": 5},
            {"terms": ["oyun", "rezilleşti"], "max_distance": 5},
            {"terms": ["oyun", "mahvoldu"], "max_distance": 5},
            {"terms": ["keyif", "almıyorum"], "max_distance": 5},
            {"terms": ["zevki", "kalmadı"], "max_distance": 5},
            {"terms": ["eğlencesi", "kalmadı"], "max_distance": 5},
            {"terms": ["işkence", "gibi"], "max_distance": 5}
        ],
        "regex": [
            r"\b(oynamayın|indirmeyin|yüklemeyin|sildim|sileceğim|silicem|kaldırıyorum|kaldırdım)\b",
            r"\b(çöp|gereksiz|boş oyun|bomboş)\b"
        ],
        "fuzzy": [
            "berbat", "rezalet", "gereksiz"
        ]
    },

    "gelistirme_onerisi": {
        "keywords": [
            "olmalı",
            "eklenmeli",
            "getirilsin",
            "düzeltilmeli",
            "düzeltin",
            "düzeltir misiniz",
            "düzeltilsin",
            "düzeltme yapın",
            "daha iyi olur",
            "çözüm bulun",
            "çözüm bulunsun",
            "artırılsın",
            "arttırılsın",
            "azaltılsın",
            "kısaltılsın",
            "lütfen",
            "rica ediyorum",
            "yenilik",
            "değiştirme yapılabilmeli",
            "daha fazlası olabilir",
            "devam ettirebilirsiniz",
            "devamını yaparsanız",
            "farklı oyunlar olsa",
            "nasıl oynanır açıklaması",
            "eklenirse",
            "olsaydı",
            "keşke",
            "değiştirilebilir",
            "geliştirilebilir",
            "eski haline getirin",
            "eski haline dönsün",
            "iyileştirin",
            "güncelleyin",
            "yardımcı olun",
            "bakarsanız sevinirim",
            "ilgilenirseniz sevinirim",
            "buna bir çözüm",
            "buna bakın",
            "kontrol edin",
            "inceleyin",
            "makul sınır",
            "sınır artırılsın",
            "ödüller artırılsın",
            "zorluk azaltılsın",
            "reklam azaltılsın",
            "yeni bölüm ekleyin",
            "yeni kart gelsin",
            "kartlarım gelsin",
            "sorun çözülsün"
        ],
        "near": [
            {"terms": ["daha", "iyi olur"], "max_distance": 5},
            {"terms": ["olsa", "iyi olur"], "max_distance": 6},
            {"terms": ["eski", "haline"], "max_distance": 5},
            {"terms": ["çözüm", "bulun"], "max_distance": 5},
            {"terms": ["düzeltin", "lütfen"], "max_distance": 6},
            {"terms": ["kontrol", "edin"], "max_distance": 5},
            {"terms": ["inceleme", "yapılmasını"], "max_distance": 5}
        ],
        "regex": [
            r"\b(eklenmeli|olmalı|getirilsin|düzeltilmeli|düzeltilsin)\b",
            r"\b(düzeltin|çözüm bulun|lütfen|keşke)\b",
            r"\b(geliştirilebilir|değiştirilebilir|iyileştirin)\b"
        ],
        "fuzzy": []
    },

    "spam_anlamsiz": {
        "keywords": [
            "dudndjd",
            "hzhhjd",
            "ndkdj",
            "full film indir",
            "ak partinin oy oranı",
            "staff bu arada",
            "usta yavuz",
            "messi",
            "anne kakam",
            "ı ı ı",
            "ok borveg"
        ],
        "near": [],
        "regex": [
            r"^[a-zğüşöçı]{1,2}$",
            r"(.)\1{5,}",
            r"^[a-zğüşöçı\s]{0,3}$",
            r"\b(full film indir|messi|ak parti)\b"
        ],
        "fuzzy": []
    }
}